name: oec-forecast-2025
channels: [conda-forge]
dependencies:
  - python=3.11
  - pandas>=2.2
  - numpy
  - pyarrow
  - statsmodels
  - lightgbm
  - scikit-learn
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - pmdarima
